# Generated by Django 2.1.5 on 2020-09-26 14:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorials',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 26, 19, 37, 43, 119630), verbose_name='date published'),
        ),
    ]
